"""
================================================================
  Запис моделі у .sli (XML формат ЛІРА САПР)
================================================================

Формат .sli — це XML (FE_Project), який ЛІРА САПР 2024 відкриває
через Файл → Імпорт → *.sli

Структура файлу (з аналізу test2.sli):
  <FE_Project Title="..." Description="">
    <DegreesOfFreedom X="1" Y="1" Z="1" UX="1" UY="1" UZ="1" />
    <NodesCoordArray NumberOfElem="N">
      <NodeCoords NdX="..." NdY="..." NdZ="..." />
      ...
    </NodesCoordArray>
    <RestrictionsArray NumberOfElem="R">
      <Restricts NdNum="..." NDOF="1|2|3" />   ← 1=X,2=Y,3=Z
      ...
    </RestrictionsArray>
    <ElementsArray NumberOfElem="E">
      <Element Type="2" Material="1|2">
        <Nodes Nd1=".." Nd2=".." Nd3=".." Nd4=".." />
      </Element>
      ...
    </ElementsArray>
    <MaterialsArray NumberOfElem="2">
      <Material Num="1" KindEl="3" H="tf" F="nu" E="E" Ro="rho" />
      <Material Num="2" KindEl="3" H="tw" F="nu" E="E" Ro="rho" />
    </MaterialsArray>
    <NodesLoadingArray NumberOfElem="...">
      <NodesLoading NumNode=".." NDOF="3" LoadType="0"
                    LoadNumber="1|2" LoadValue="..." LocalSys="0" />
      ...
    </NodesLoadingArray>
    <ElemHingeArray    NumberOfElem="0" />
    <NodeHingeArray    NumberOfElem="0" />
    <EccentricityArray NumberOfElem="0" />
    <ElemLoadingArray  NumberOfElem="0" />
  </FE_Project>
"""

import os
from typing import List, Tuple

from ibeam_sli_generator import BeamParams, Node, Quad


def _fmt(v: float) -> str:
    """Форматує число: без зайвих нулів, але з достатньою точністю."""
    if v == 0.0:
        return "0"
    s = f"{v:.8g}"
    return s


def write_sli(p: BeamParams,
              nodes: List[Node],
              elements: List[Quad],
              forces_lc1: List[Tuple[int, float]],
              forces_lc2: List[Tuple[int, float]],
              filepath: str):
    """Записує модель у форматі .sli (XML FE_Project)."""

    lines = []

    def ln(s):
        lines.append(s)

    ln('<?xml version="1.0" standalone="yes"?>')
    ln('<!--Generated by ibeam_sli_generator.py-->')
    ln(f'<FE_Project Title="{p.name}" Description="">')
    ln('  <DegreesOfFreedom X="1" Y="1" Z="1" UX="1" UY="1" UZ="1" />')

    # ── Вузли ──────────────────────────────────────────────────
    ln(f'  <NodesCoordArray NumberOfElem="{len(nodes)}">')
    for n in nodes:
        ln(f'    <NodeCoords NdX="{_fmt(n.x)}" NdY="{_fmt(n.y)}" NdZ="{_fmt(n.z)}" />')
    ln('  </NodesCoordArray>')

    # ── В'язі ──────────────────────────────────────────────────
    # Ліва опора (Y=0): закріплення X(1), Y(2), Z(3)
    # Права опора (Y=L): закріплення X(1), Z(3) — рухома по Y
    support_start = [n.id for n in nodes if abs(n.y) < 1e-6]
    support_end   = [n.id for n in nodes if abs(n.y - p.L) < 1e-6]

    restrictions = []
    for nid in support_start:
        restrictions += [(nid, 1), (nid, 2), (nid, 3)]
    for nid in support_end:
        restrictions += [(nid, 1), (nid, 3)]

    ln(f'  <RestrictionsArray NumberOfElem="{len(restrictions)}">')
    for nid, dof in restrictions:
        ln(f'    <Restricts NdNum="{nid}" NDOF="{dof}" />')
    ln('  </RestrictionsArray>')

    # ── Елементи ───────────────────────────────────────────────
    ln(f'  <ElementsArray NumberOfElem="{len(elements)}">')
    for e in elements:
        ln(f'    <Element Type="2" Material="{e.mat}">')
        if e.n4:
            ln(f'      <Nodes Nd1="{e.n1}" Nd2="{e.n2}" Nd3="{e.n3}" Nd4="{e.n4}" />')
        else:
            ln(f'      <Nodes Nd1="{e.n1}" Nd2="{e.n2}" Nd3="{e.n3}" />')
        ln('    </Element>')
    ln('  </ElementsArray>')

    # ── Матеріали ──────────────────────────────────────────────
    # KindEl=3 — пластина (з test2.sli)
    # H — товщина, F — nu, E — модуль, Ro — щільність
    ln('  <MaterialsArray NumberOfElem="2">')
    ln(f'    <Material Num="1" KindEl="3" H="{_fmt(p.tf)}" F="{_fmt(p.nu)}" '
       f'E="{_fmt(p.E)}" Ro="{_fmt(p.rho)}" />')
    ln(f'    <Material Num="2" KindEl="3" H="{_fmt(p.tw)}" F="{_fmt(p.nu)}" '
       f'E="{_fmt(p.E)}" Ro="{_fmt(p.rho)}" />')
    ln('  </MaterialsArray>')

    # ── Навантаження ───────────────────────────────────────────
    # NDOF=3 → Z (вертикаль), LoadType=0 → статичне, LocalSys=0 → глобальна
    # LoadNumber=1 → LC1, LoadNumber=2 → LC2
    # LoadValue в кН (негативне → вниз)
    all_loads = (
        [(nid, f, 1) for nid, f in forces_lc1] +
        [(nid, f, 2) for nid, f in forces_lc2]
    )
    ln(f'  <NodesLoadingArray NumberOfElem="{len(all_loads)}">')
    for nid, fval, lc in all_loads:
        ln(f'    <NodesLoading NumNode="{nid}" NDOF="3" LoadType="0" '
           f'LoadNumber="{lc}" LoadValue="{_fmt(fval)}" LocalSys="0" />')
    ln('  </NodesLoadingArray>')

    # ── Порожні блоки (обов'язкові для ЛІРА) ──────────────────
    ln('  <ElemHingeArray NumberOfElem="0" />')
    ln('  <NodeHingeArray NumberOfElem="0" />')
    ln('  <EccentricityArray NumberOfElem="0" />')
    ln('  <ElemLoadingArray NumberOfElem="0" />')
    ln('</FE_Project>')

    os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
    with open(filepath, 'w', encoding='utf-8', newline='\r\n') as f:
        f.write('\n'.join(lines))


def write_plate_sli(title: str,
                    nodes: List[Node],
                    elements: List[Quad],
                    materials: List[dict],
                    filepath: str):
    """Записує модель плити у .sli (XML FE_Project) без навантажень.

    materials — список словників:
        [{"num": 1, "H": 0.01, "F": 0.28, "E": 2.02027e7, "Ro": 7850}, ...]
    """
    lines = []

    def ln(s):
        lines.append(s)

    ln('<?xml version="1.0" standalone="yes"?>')
    ln('<!--Generated by plate_gmsh_sli.py-->')
    ln(f'<FE_Project Title="{title}" Description="">')
    ln('  <DegreesOfFreedom X="1" Y="1" Z="1" UX="1" UY="1" UZ="1" />')

    # ── Вузли ──
    ln(f'  <NodesCoordArray NumberOfElem="{len(nodes)}">')
    for n in nodes:
        ln(f'    <NodeCoords NdX="{_fmt(n.x)}" NdY="{_fmt(n.y)}" NdZ="{_fmt(n.z)}" />')
    ln('  </NodesCoordArray>')

    # ── Без в'язей ──
    ln('  <RestrictionsArray NumberOfElem="0" />')

    # ── Елементи (quad / triangle) ──
    ln(f'  <ElementsArray NumberOfElem="{len(elements)}">')
    for e in elements:
        ln(f'    <Element Type="2" Material="{e.mat}">')
        if e.n4:
            ln(f'      <Nodes Nd1="{e.n1}" Nd2="{e.n2}" Nd3="{e.n3}" Nd4="{e.n4}" />')
        else:
            ln(f'      <Nodes Nd1="{e.n1}" Nd2="{e.n2}" Nd3="{e.n3}" />')
        ln('    </Element>')
    ln('  </ElementsArray>')

    # ── Матеріали ──
    ln(f'  <MaterialsArray NumberOfElem="{len(materials)}">')
    for m in materials:
        ln(f'    <Material Num="{m["num"]}" KindEl="3" H="{_fmt(m["H"])}" '
           f'F="{_fmt(m["F"])}" E="{_fmt(m["E"])}" Ro="{_fmt(m["Ro"])}" />')
    ln('  </MaterialsArray>')

    # ── Без навантажень ──
    ln('  <NodesLoadingArray NumberOfElem="0" />')

    # ── Порожні блоки ──
    ln('  <ElemHingeArray NumberOfElem="0" />')
    ln('  <NodeHingeArray NumberOfElem="0" />')
    ln('  <EccentricityArray NumberOfElem="0" />')
    ln('  <ElemLoadingArray NumberOfElem="0" />')
    ln('</FE_Project>')

    os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
    with open(filepath, 'w', encoding='utf-8', newline='\r\n') as f:
        f.write('\n'.join(lines))
